services:
  rc2d-builder:
    container_name: rc2d_slr3_sniper
    image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:3.0.20250408.124536
    working_dir: /build
    volumes:
      - ./:/build:rw
      - ./docker-build-output:/build/build/Release:rw
    environment:
      - CMAKE_BUILD_TYPE=Release
      - RC2D_PLATFORM=SLR3-SNIPER
    command: >
      bash -c "apt update && apt install -y patchelf &&
      mkdir -p build && cd build &&
      cmake .. -DRC2D_BUILD_EXAMPLES=ON -DRC2D_GPU_SHADER_HOT_RELOAD_ENABLED=OFF
      -DRC2D_DATA_MODULE_ENABLED=ON -DRC2D_NET_MODULE_ENABLED=ON -DRC2D_ONNX_MODULE_ENABLED=ON
      -DRC2D_ASSERT_LEVEL=3 -DCMAKE_BUILD_TYPE=Release &&
      cmake --build . --config Release --parallel &&

      # Patch RPATH pour que l'executable cherche les bibliothèques dans le même répertoire
      # que lui-même, et non dans le répertoire de l'exécutable de la commande
      patchelf --set-rpath '$ORIGIN' --force-rpath Release/rc2d_example &&

      echo 'patchelf applied, checking ldd:' &&
      ldd Release/rc2d_example"